# 1. NOME DO FUNCIONARIO E TODOS OS ITENS QUE ELE JÁ VENDEU.
# 2. NOME DO CLIENTE E OS PRODUTOS COMPRADOS POR ELE.
# 3. PRODUTO MAIS VENDIDO.
# 4. GRUPO DOS PRODUTOS QUE MAIS VENDEU.
# 5. NOME DO FORNECEDOR E DO ITEM MAIS COMPRADO.
# 7. CONSULTA QUE MOSTRA AS COMPRAS DE UM FORNECEDOR ESPECÍFICO, JUNTAMENTE COM AS INFORMAÇÕES DO FUNCIONARIO RESPONSÁVEL, E OS PRODUTOS COMPRADOS
# 8. MOSTRAR A VENDA EM QUE FOI VENDIDO PRODUTOS DE ID = 8, E QUAIS SÃO OS CLIENTES QUE O COMPRARAM
# 9. MOSTRAR OS PRODUTOS E AS INFORMAÇÕES DOS SEUS RESPECTIVOS FORNECEDORES
# 10. CLIENTE COM MAIOR IDADE
# 11. O NOME DO CLIENTE QUE MAIS COMPROU